#!/bin/sh
ROOT_DIR=${1:-${ROOTSYS}}
JOBS=${2:-4}

PYTHIA_VER="8235"
HEPMC2_VER="2.06.09"
LHAPDF6_VER="6.2.1"

CURDIR=$(pwd)
DOWNLOAD_DIR=${CURDIR}/Downloads
mkdir -v ${DOWNLOAD_DIR}

# Install HepMC2
HEPMC2_DIR=${CURDIR}/HepMC2
if [ ! -f ${CURDIR}/hepmc${HEPMC2_VER}.tgz ] 
then
    wget http://hepmc.web.cern.ch/hepmc/releases/hepmc${HEPMC2_VER}.tgz -P ${DOWNLOAD_DIR}
fi

if [ ! -d ${CURDIR}/HepMC2 ]
then
  tar -xzf ${DOWNLOAD_DIR}/hepmc${HEPMC2_VER}.tgz
  cd hepmc${HEPMC2_VER}
  ./configure --prefix=${HEPMC2_DIR} \
              --with-momentum=GEV \
              --with-length=MM
  make -j${JOBS}
  make check
  make install
  cd ${CURDIR}
fi
mv hepmc${HEPMC2_VER} ${DOWNLOAD_DIR}


# Install LHAPDF6
LHAPDF6_DIR=${CURDIR}/LHAPDF6
mkdir -v ${LHAPDF6_DIR}
wget http://www.hepforge.org/archive/lhapdf/LHAPDF-${LHAPDF6_VER}.tar.gz -P ${DOWNLOAD_DIR}
tar xf ${DOWNLOAD_DIR}/LHAPDF-${LHAPDF6_VER}.tar.gz
cd LHAPDF-${LHAPDF6_VER}
./configure --prefix=${LHAPDF6_DIR}
make -j${JOBS}
make install
cd ${CURDIR}
mv LHAPDF-${LHAPDF6_VER} ${DOWNLOAD_DIR}


# Download NNPDF for example2
wget http://pcteserver.mi.infn.it/~nnpdf/nnpdf30/NNPDF30_lo_as_0130.tar.gz -P ${DOWNLOAD_DIR}
tar xvfz ${DOWNLOAD_DIR}/NNPDF30_lo_as_0130.tar.gz -C ${LHAPDF6_DIR}/share/LHAPDF


# Install Pythia8
if [ ! -f ${CURDIR}/pythia${PYTHIA_VER}.tgz ]
then
    wget http://home.thep.lu.se/~torbjorn/pythia8/pythia${PYTHIA_VER}.tgz -P ${DOWNLOAD_DIR}
fi

tar -xzf ${DOWNLOAD_DIR}/pythia${PYTHIA_VER}.tgz 
cd ${CURDIR}/pythia${PYTHIA_VER}
./configure --with-root=${ROOT_DIR} \
            --with-hepmc2=${HEPMC2_DIR} \
            --with-lhapdf6=${LHAPDF6_DIR}
make -j${JOBS}

cd ${CURDIR}

cp -v pythia${PYTHIA_VER}/examples/Makefile.inc Examples/
